### ISSUE TITLE
Can't enter API key

### ISSUE THREAD

**Issue by ARazaMaths** [adamyodinsky/TerminalGPT#19]
**Can't enter API key after `terminalgpt install`.**

**To Reproduce**
1. `pip install terminalgpt -U`
2. `terminalgpt install`
3. Get output
```
OpenAI API key is missing!
Please install the chatbot api key first with 'terminalgpt install' command.
```

**Expected behavior**
Asks for API key.

**Comment by adamyodinsky** [comment]
Hi @ARazaMaths 

This bug was introduced in the v1.0.2 release and was fixed in v1.0.14.
Unfortunately, I was not aware for more than 2 weeks.

You can fix it by reinstalling `pip install terminalgpt -U --user`. This will install the latest version of TermninalGPT which is the most stable version so far, with better error handling, and some small improvements that should improve the overall experience.

Cheers
